### PR TITLE
Fix eval-file-pyqt5-set-value

### PR DESCRIPTION
**Pull request by galou**

### CODE REVIEW

**Comment by aoloe** [comment]
thanks for the fixes!

**Comment by aoloe** [comment]
sorry, the `_` was needed. i've re-added it in the next commit.

**Comment by galou** [comment]
Yes, I added the `_` because `locals is a reserved word. By the way, how is it possible that `set_the_answer` is available in `main` but not in `get_the_value`? Thanks

**Comment by aoloe** [comment]
yeah, i've seen it later.  
i've now renamed it to `outer_locals`.

the reason why the injected function is not available inside of the other function, is related to the way pybind11 runs the python code.  
i don't have a deep knowledge about it, but i've been told that it's called as if it's inside of a class.

some notes about it are in the README file in the same directory : - )

**Pull request merged**
